### ISSUE TITLE
Problems starting Comfy with this custom node

### ISSUE THREAD

**Issue by Maelstrom2014** [florestefano1975/ComfyUI-HiDiffusion#1]
Traceback (most recent call last):
  File "C:\ai\comfyui\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI-HiDiffusion\__init__.py", line 7, in <module>
    from hidiffusion import apply_hidiffusion, remove_hidiffusion
ModuleNotFoundError: No module named 'hidiffusion'

**Comment by florestefano1975** [comment]
"pip install hidiffusion" 😉
